### ISSUE TITLE
provide a way to send @T@ as parameter to <metadata_progname>

### ISSUE THREAD

**Issue by elonden** [xiph/ezstream#19]
If the filename could be send to the <metadata_progname> as a parameter it would provide the option to extract the id3 info out of an MP3 and use that as meta data. This would provide the ability to enrich the meta-data with more info than just the artist and title.

Not sure if that is possible but would be very useful.

Thank you.

**Comment by mgrimm** [comment]
Hi elonden,

On the topic of <metadata_progname/>, I found it was still erroneously mentioned in the documentation in one place. Thanks for the pointer; I removed it.
On solving your issue, if both metadata->program and the playlist program query the same database (which can be simple flat files or something fancy), you can easily do something like the above. When scripting ezstream, it is better to not have it play the role of or be a proxy for the single source of truth. It should just do what it's told. Because of this, I'm not planning to change this data flow.

Thanks,
-Moritz
