### ISSUE TITLE
How to uninstall libshout?

### ISSUE THREAD

**Issue by joaoherberto** [xiph/ezstream#2]
I installed libeshout-2.4.1 and now even though I installed libshout2.2.2, when configuring ezstream, it is still only finding 2.4 and continually gives error "requires libshout-2.2.x" . Help...

**Comment by mgrimm** [comment]
The error message is misleading (fixed now), since it doesn't require a specific version of libshout other than 2.2.0 _or newer_.

This can be caused by a broken or incomplete libshout installation (missing development header files), or a defect in the ezstream build system.

Please attach config.log for further debugging.

**Comment by mgrimm** [comment]
Case gone cold.
