### ISSUE TITLE
ezstream 1.0.1 does not start without a "default" stream

### ISSUE THREAD

**Issue by elonden** [xiph/ezstream#21]
So this did my head in for while. When a single stream is configured and the parameter <name> is used ezstream refuses to start and basically exists with:

ezstream[3214445]: stream: default: no configuration

When I remove the <name> parameter in the xml file that stream will become the "default" and it works OK. 

Not sure if this is done by default/design but if it is than a few lines in the man-page would've been helpful.

**Comment by mgrimm** [comment]
Hi elonden,

This is indeed by design; with v1 I changed the configuration file semantics to support multiple concurrent streams, which is one of the main drivers for v1 version bump in the first place. It's _the_ feature I want to see in ezstream, and the v0 config file format just wouldn't cut it. However, the actual implementation requires significant work and I can't give a timeline for it.
It's good that ezstream apparently gave enough feedback to help resolve this issue, and this caveat is currently "documented" in the ezstream-full.xml example configuration file.
After giving this some thought, I am hesitant to implementing a change in the documentation or ezstream itself. The former is not the right place, as the configuration file format and its documentation does not have an issue. The latter would mean a change to "support the missing support of multiple concurrent streams", e.g. with a dedicated message, which is absurd. I'd rather take the pain of keeping this as a "known issue".
I'll keep your report open so others can see this. Thank you!

Best regards,
-Moritz

**Comment by elonden** [comment]
Hello Moritz,

I have no objection of requiring a "default" stream or at least one a stream without a name. The issue is just I missed this in the documentation and the error message may be a bit more descriptive.

**Comment by elonden** [comment]
Looking at the "example-full.xml" I see the explanation. Would it be simply possible to temporarily adjust the error-message to be a bit more descriptive. When you reach the stage where multiple streams are supported it's relatively easy to change that again.

**Comment by mgrimm** [comment]
A few months later I now think this warrants a sentence in the manual. I still don't want to change the error message for consistency reasons. ;)

Thanks!

**Comment by tavdog** [comment]
I looked at full.xml but I still don't know how to fix this damn problem.  Ok so I had to rebuild my config file for the new version 1.0.  Maybe a little blurb in the readme about the entirely new format of the config format is warranted.  I wasn't aware that ezstream even got updated and suddenly my stream wouldn't start with the most vague error message possible.
